root = "."
testdata_dir = "testdata"
tmp_dir = "/tmp"

[build]
  args_bin = []
  bin = "/tmp/main"
  cmd = "go build -o /tmp/main cmd/books/main.go"
  delay = 1000
  exclude_dir = ["scans", "api", "docker", "sql"]
  exclude_file = [".env.example", ".env", "go.mod", "go.sum", ".gitignore", ".air.toml", "Makefile", "README.md", "TODO.md"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "/tmp/air-build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
